version: '3'
services:
  db:
    image: neo4j:3.2.3
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    volumes:
      - ./db/dbms:/data/dbms
      - ./db/conf:/conf
      - ./db/plugins:/plugins

  elasticsearch:
    image: elasticsearch:2.4.6-alpine
    ports:
      - 9200:9200

  backend:
    build:
      context: .
      dockerfile: ./compose/nodejs/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./src:/app/src
    links:
      - db
    depends_on:
      - elasticsearch
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: ./compose/react/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    depends_on:
      - backend
    env_file:
      - .env
